import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, TextInput, ActivityIndicator, Alert, StatusBar, Platform } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';
import Animated, { useSharedValue, useAnimatedStyle, withTiming, withSpring } from 'react-native-reanimated';
import { ChevronLeft, FileCheck, Share2, Clock, User, Stethoscope, Pill, Calendar, ClipboardList, RefreshCw } from 'lucide-react-native';
import { theme, getSpringConfig } from '../constants/theme';
import ClinicalCanvas from '../components/ClinicalCanvas';
import useStore from '../store/useStore';
import { sendRoomMessage } from '../services/socket';
import AnimatedMount from '../components/AnimatedMount';
import AnimatedPressable from '../components/AnimatedPressable';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const DischargeSummaryScreen = ({ route, navigation }) => {
  const { patientId } = route.params;
  const patients = useStore((state) => state.patients);
  const { generateDischarge, fetchDischarge, getOrCreatePatientChat } = useStore();
  
  const patient = patients.find(p => p.recordID === patientId);

  const insets = useSafeAreaInsets();


  const [summaries, setSummaries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [followUp, setFollowUp] = useState('Follow up in OPD after 1 week. Report immediately if any complications arise.');
  
  const [toastMessage, setToastMessage] = useState('');
  const [showToast, setShowToast] = useState(false);
  const toastOpacity = useSharedValue(0);
  const toastTranslateY = useSharedValue(-50);

  const triggerToast = (msg) => {
    setToastMessage(msg);
    setShowToast(true);
    toastOpacity.value = withTiming(1, { duration: 300 });
    toastTranslateY.value = withSpring(0, getSpringConfig({ damping: 22, stiffness: 150 }));

    setTimeout(() => {
      toastOpacity.value = withTiming(0, { duration: 300 });
      toastTranslateY.value = withTiming(-50, { duration: 300 });
    }, 2800);
  };

  const animatedToastStyle = useAnimatedStyle(() => {
    return {
      opacity: toastOpacity.value,
      transform: [{ translateY: toastTranslateY.value }],
    };
  });

  useEffect(() => {
    loadSummaries();
  }, []);

  const loadSummaries = async () => {
    setLoading(true);
    const res = await fetchDischarge(patientId);
    if (res.success) {
      setSummaries(res.summaries);
    }
    setLoading(false);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    const res = await generateDischarge(patientId, followUp);
    if (res.success) {
      setSummaries(prev => [res.summary, ...prev]);
      triggerToast('Discharge summary generated & saved.');
    } else {
      Alert.alert('Error', res.error || 'Failed to generate discharge summary.');
    }
    setGenerating(false);
  };

  const handleShareToChat = async (summary) => {
    setSharing(true);
    const chatRes = await getOrCreatePatientChat(patientId);
    if (chatRes.success) {
      const text = `📋 DISCHARGE SUMMARY\n━━━━━━━━━━━━━━━━━━━\n👤 ${patient?.fullName || 'Patient'}\n📅 Admitted: ${summary.admissionDate}\n📅 Discharged: ${summary.dischargeDate}\n🔬 Diagnosis: ${summary.diagnosis}\n🏥 Procedures: ${summary.procedures || 'None'}\n💊 Medications: ${summary.medicationsOnDischarge || 'None'}\n📝 Follow-up: ${summary.followUpInstructions}\n━━━━━━━━━━━━━━━━━━━\nGenerated by ${summary.generatedBy}`;
      sendRoomMessage(chatRes.room.id, text, null, null);
      triggerToast('Discharge summary shared to chat.');
    } else {
      Alert.alert('Error', 'Could not open discussion channel.');
    }
    setSharing(false);
  };

  const renderSummaryCard = (summary, idx) => (
    <View key={summary.id || idx} style={styles.summaryCard}>
      <View style={styles.summaryHeader}>
        <View style={styles.summaryBadge}>
          <FileCheck size={16} color="#047857" />
          <Text style={styles.summaryBadgeText}>Discharge Summary</Text>
        </View>
        <TouchableOpacity 
          style={styles.shareBtn}
          onPress={() => handleShareToChat(summary)}
          disabled={sharing}
        >
          {sharing ? (
            <ActivityIndicator size="small" color={theme.colors.primary} />
          ) : (
            <>
              <Share2 size={14} color={theme.colors.primary} />
              <Text style={styles.shareBtnText}>Share</Text>
            </>
          )}
        </TouchableOpacity>
      </View>

      <View style={styles.summarySection}>
        <View style={styles.summaryRow}>
          <Calendar size={14} color="#6B7280" />
          <Text style={styles.summaryLabel}>Admission Date</Text>
          <Text style={styles.summaryValue}>{summary.admissionDate}</Text>
        </View>
        <View style={styles.summaryRow}>
          <Calendar size={14} color="#6B7280" />
          <Text style={styles.summaryLabel}>Discharge Date</Text>
          <Text style={styles.summaryValue}>{summary.dischargeDate}</Text>
        </View>
      </View>

      <View style={styles.summaryDivider} />

      <View style={styles.summarySection}>
        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <Stethoscope size={14} color="#3B82F6" />
            <Text style={styles.fieldTitle}>Diagnosis</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.diagnosis}</Text>
        </View>

        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <ClipboardList size={14} color="#8B5CF6" />
            <Text style={styles.fieldTitle}>Procedures</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.procedures || 'None'}</Text>
        </View>

        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <Pill size={14} color="#EF4444" />
            <Text style={styles.fieldTitle}>Medications on Discharge</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.medicationsOnDischarge || 'None'}</Text>
        </View>

        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <RefreshCw size={14} color="#F59E0B" />
            <Text style={styles.fieldTitle}>Follow-up Instructions</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.followUpInstructions}</Text>
        </View>
      </View>

      <View style={styles.summaryFooter}>
        <View style={styles.footerRow}>
          <User size={12} color="#9CA3AF" />
          <Text style={styles.footerText}>Generated by {summary.generatedBy}</Text>
        </View>
        <View style={styles.footerRow}>
          <Clock size={12} color="#9CA3AF" />
          <Text style={styles.footerText}>{new Date(summary.createdAt).toLocaleString()}</Text>
        </View>
      </View>
    </View>
  );

  return (
    <ClinicalCanvas style={[styles.container, { paddingBottom: 0 }]}>
      <StatusBar barStyle="dark-content" />
      
      {/* Toast Alert */}
      {showToast && (
        <Animated.View style={[styles.toastContainer, animatedToastStyle]}>
          <Text style={styles.toastText}>{toastMessage}</Text>
        </Animated.View>
      )}

      <View style={styles.header}>
        <AnimatedPressable 
          onPress={() => navigation.goBack()} 
          style={styles.backBtn}
          hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
          accessibilityLabel="Go back"
          accessibilityRole="button"
        >
          <ChevronLeft size={24} color={theme.colors.primary} />
        </AnimatedPressable>
        <Text style={styles.headerTitle}>Discharge Summary</Text>
        <View style={{ width: 32 }} />
      </View>

      <KeyboardAwareScrollView
        style={styles.scrollContainer}
        contentContainerStyle={[styles.scrollContent, { paddingBottom: Math.max(insets.bottom, 80) }]} 
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
        bottomOffset={40}
      >
        {/* Patient Banner */}
        <AnimatedMount slide delay={0}>
          <View style={styles.patientBanner}>
            <View style={styles.patientAvatar}>
              <Text style={styles.avatarText}>{patient?.fullName?.charAt(0) || '?'}</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.patientName}>{patient?.fullName || 'Unknown'}</Text>
              <Text style={styles.patientDiag}>{patient?.diagnosis || 'No diagnosis'}</Text>
            </View>
            <View style={[styles.statusBadge, { backgroundColor: patient?.status === 'Discharged' ? '#D1FAE5' : '#EFF6FF' }]}>
              <Text style={[styles.statusText, { color: patient?.status === 'Discharged' ? '#047857' : '#3B82F6' }]}>
                {patient?.status || 'Admitted'}
              </Text>
            </View>
          </View>
        </AnimatedMount>

        {/* Generate New Summary Section */}
        <AnimatedMount slide delay={80}>
          <View style={styles.generateSection}>
            <Text style={styles.sectionTitle}>Generate New Summary</Text>
            <Text style={styles.inputLabel}>Follow-up Instructions</Text>
            <TextInput
              style={styles.followUpInput}
              placeholder="Enter follow-up instructions..."
              placeholderTextColor={theme.colors.textSecondary}
              value={followUp}
              onChangeText={setFollowUp}
              multiline
              numberOfLines={3}
            />
            <AnimatedPressable 
              style={styles.generateBtn}
              onPress={handleGenerate}
              disabled={generating}
            >
              {generating ? (
                <ActivityIndicator size="small" color="#FFF" />
              ) : (
                <>
                  <FileCheck size={18} color="#FFF" />
                  <Text style={styles.generateBtnText}>Generate & Save Summary</Text>
                </>
              )}
            </AnimatedPressable>
          </View>
        </AnimatedMount>

        {/* Existing Summaries */}
        <Text style={styles.sectionTitle}>Previous Summaries</Text>

        {generating && (
          <AnimatedMount style={styles.generatingCard}>
            <ActivityIndicator size="small" color={theme.colors.primary} style={{ marginRight: 10 }} />
            <Text style={styles.generatingText}>Drafting clinical discharge summary...</Text>
          </AnimatedMount>
        )}
        
        {loading ? (
          <View style={styles.loaderBox}>
            <ActivityIndicator size="small" color={theme.colors.primary} />
            <Text style={styles.loaderText}>Loading summaries...</Text>
          </View>
        ) : summaries.length === 0 && !generating ? (
          <View style={styles.emptyBox}>
            <FileCheck size={32} color="#D1D5DB" />
            <Text style={styles.emptyText}>No discharge summaries generated yet.</Text>
          </View>
        ) : (
          summaries.map((s, idx) => (
            <AnimatedMount key={s.id || idx} delay={Math.min(idx * 80, 500)}>
              {renderSummaryCard(s, idx)}
            </AnimatedMount>
          ))
        )}
      </KeyboardAwareScrollView>
    </ClinicalCanvas>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollContainer: { flex: 1 },
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.sm,
    backgroundColor: theme.colors.surface, borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  backBtn: { padding: theme.spacing.xs },
  headerTitle: { ...theme.typography.h2, color: theme.colors.primary, fontWeight: '800' },
  scrollContent: { padding: theme.spacing.lg, paddingBottom: 80 },

  patientBanner: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.xl, padding: theme.spacing.lg, marginBottom: theme.spacing.lg,
  },
  patientAvatar: {
    width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center', justifyContent: 'center', marginRight: theme.spacing.md,
  },
  avatarText: { fontSize: 18, fontWeight: '800', color: '#FFF' },
  patientName: { fontSize: 16, fontWeight: '800', color: '#FFF' },
  patientDiag: { fontSize: 12, color: '#93C5FD', fontWeight: '500' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 11, fontWeight: '700' },

  generateSection: {
    backgroundColor: '#FFF', borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.xl, marginBottom: theme.spacing.xl,
    borderWidth: 1, borderColor: '#E2E8F0',
  },
  sectionTitle: { ...theme.typography.h3, marginBottom: theme.spacing.md },
  inputLabel: { ...theme.typography.label, marginBottom: theme.spacing.xs, color: theme.colors.textSecondary },
  followUpInput: {
    backgroundColor: '#F8FAFC', borderRadius: theme.borderRadius.md, borderWidth: 1,
    borderColor: '#E2E8F0', padding: theme.spacing.md, ...theme.typography.body,
    minHeight: 80, textAlignVertical: 'top', marginBottom: theme.spacing.md,
  },
  generateBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#047857', borderRadius: theme.borderRadius.lg,
    paddingVertical: 14, gap: 8,
  },
  generateBtnText: { color: '#FFF', fontSize: 14, fontWeight: '700' },

  summaryCard: {
    backgroundColor: '#FFF', borderRadius: theme.borderRadius.xl,
    borderWidth: 1, borderColor: '#E2E8F0', marginBottom: theme.spacing.lg, overflow: 'hidden',
  },
  summaryHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: '#F0FDF4', paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.md,
    borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  summaryBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  summaryBadgeText: { fontSize: 13, fontWeight: '700', color: '#047857' },
  shareBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: '#EFF6FF' },
  shareBtnText: { fontSize: 12, fontWeight: '700', color: theme.colors.primary },

  summarySection: { padding: theme.spacing.lg },
  summaryRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  summaryLabel: { fontSize: 12, color: '#6B7280', fontWeight: '600', flex: 1 },
  summaryValue: { fontSize: 13, fontWeight: '700', color: '#1F2937' },
  summaryDivider: { height: 1, backgroundColor: '#F1F5F9', marginHorizontal: theme.spacing.lg },

  fieldBlock: { marginBottom: theme.spacing.md },
  fieldHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  fieldTitle: { fontSize: 12, fontWeight: '700', color: '#374151' },
  fieldContent: { fontSize: 13, color: '#4B5563', lineHeight: 20, paddingLeft: 20 },

  summaryFooter: {
    backgroundColor: '#F8FAFC', paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.sm,
    borderTopWidth: 1, borderTopColor: '#F1F5F9', flexDirection: 'row', justifyContent: 'space-between',
  },
  footerRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  footerText: { fontSize: 10, color: '#9CA3AF', fontWeight: '500' },

  loaderBox: { alignItems: 'center', paddingVertical: 40 },
  loaderText: { marginTop: 8, color: theme.colors.textSecondary, fontSize: 12 },
  emptyBox: { alignItems: 'center', paddingVertical: 40, gap: 8 },
  emptyText: { color: '#9CA3AF', fontSize: 13 },
  toastContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 20,
    left: theme.spacing.lg,
    right: theme.spacing.lg,
    backgroundColor: '#047857',
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    zIndex: 100,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  toastText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: theme.typography.fontFamily,
  },
  generatingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.lg,
  },
  generatingText: {
    color: '#065F46',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: theme.typography.fontFamily,
  },
});

export default DischargeSummaryScreen;
