import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, ActivityIndicator, Alert, StatusBar } from 'react-native';
import { ChevronLeft, FileCheck, Share2, Clock, User, Stethoscope, Pill, Calendar, ClipboardList, RefreshCw } from 'lucide-react-native';
import { theme } from '../constants/theme';
import ClinicalCanvas from '../components/ClinicalCanvas';
import useStore from '../store/useStore';
import { sendRoomMessage } from '../services/socket';

const DischargeSummaryScreen = ({ route, navigation }) => {
  const { patientId } = route.params;
  const patients = useStore((state) => state.patients);
  const { generateDischarge, fetchDischarge, getOrCreatePatientChat } = useStore();
  
  const patient = patients.find(p => p.recordID === patientId);

  const [summaries, setSummaries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [sharing, setSharing] = useState(false);
  const [followUp, setFollowUp] = useState('Follow up in OPD after 1 week. Report immediately if any complications arise.');

  useEffect(() => {
    loadSummaries();
  }, []);

  const loadSummaries = async () => {
    setLoading(true);
    const res = await fetchDischarge(patientId);
    if (res.success) {
      setSummaries(res.summaries);
    }
    setLoading(false);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    const res = await generateDischarge(patientId, followUp);
    if (res.success) {
      setSummaries(prev => [res.summary, ...prev]);
      Alert.alert('Success', 'Discharge summary generated and saved.');
    } else {
      Alert.alert('Error', res.error || 'Failed to generate discharge summary.');
    }
    setGenerating(false);
  };

  const handleShareToChat = async (summary) => {
    setSharing(true);
    const chatRes = await getOrCreatePatientChat(patientId);
    if (chatRes.success) {
      const text = `📋 DISCHARGE SUMMARY\n━━━━━━━━━━━━━━━━━━━\n👤 ${patient?.fullName || 'Patient'}\n📅 Admitted: ${summary.admissionDate}\n📅 Discharged: ${summary.dischargeDate}\n🔬 Diagnosis: ${summary.diagnosis}\n🏥 Procedures: ${summary.procedures || 'None'}\n💊 Medications: ${summary.medicationsOnDischarge || 'None'}\n📝 Follow-up: ${summary.followUpInstructions}\n━━━━━━━━━━━━━━━━━━━\nGenerated by ${summary.generatedBy}`;
      sendRoomMessage(chatRes.room.id, text, null, null);
      Alert.alert('Shared', 'Discharge summary sent to patient discussion channel.');
    } else {
      Alert.alert('Error', 'Could not open discussion channel.');
    }
    setSharing(false);
  };

  const renderSummaryCard = (summary, idx) => (
    <View key={summary.id || idx} style={styles.summaryCard}>
      <View style={styles.summaryHeader}>
        <View style={styles.summaryBadge}>
          <FileCheck size={16} color="#047857" />
          <Text style={styles.summaryBadgeText}>Discharge Summary</Text>
        </View>
        <TouchableOpacity 
          style={styles.shareBtn}
          onPress={() => handleShareToChat(summary)}
          disabled={sharing}
        >
          {sharing ? (
            <ActivityIndicator size="small" color={theme.colors.primary} />
          ) : (
            <>
              <Share2 size={14} color={theme.colors.primary} />
              <Text style={styles.shareBtnText}>Share</Text>
            </>
          )}
        </TouchableOpacity>
      </View>

      <View style={styles.summarySection}>
        <View style={styles.summaryRow}>
          <Calendar size={14} color="#6B7280" />
          <Text style={styles.summaryLabel}>Admission Date</Text>
          <Text style={styles.summaryValue}>{summary.admissionDate}</Text>
        </View>
        <View style={styles.summaryRow}>
          <Calendar size={14} color="#6B7280" />
          <Text style={styles.summaryLabel}>Discharge Date</Text>
          <Text style={styles.summaryValue}>{summary.dischargeDate}</Text>
        </View>
      </View>

      <View style={styles.summaryDivider} />

      <View style={styles.summarySection}>
        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <Stethoscope size={14} color="#3B82F6" />
            <Text style={styles.fieldTitle}>Diagnosis</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.diagnosis}</Text>
        </View>

        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <ClipboardList size={14} color="#8B5CF6" />
            <Text style={styles.fieldTitle}>Procedures</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.procedures || 'None'}</Text>
        </View>

        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <Pill size={14} color="#EF4444" />
            <Text style={styles.fieldTitle}>Medications on Discharge</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.medicationsOnDischarge || 'None'}</Text>
        </View>

        <View style={styles.fieldBlock}>
          <View style={styles.fieldHeader}>
            <RefreshCw size={14} color="#F59E0B" />
            <Text style={styles.fieldTitle}>Follow-up Instructions</Text>
          </View>
          <Text style={styles.fieldContent}>{summary.followUpInstructions}</Text>
        </View>
      </View>

      <View style={styles.summaryFooter}>
        <View style={styles.footerRow}>
          <User size={12} color="#9CA3AF" />
          <Text style={styles.footerText}>Generated by {summary.generatedBy}</Text>
        </View>
        <View style={styles.footerRow}>
          <Clock size={12} color="#9CA3AF" />
          <Text style={styles.footerText}>{new Date(summary.createdAt).toLocaleString()}</Text>
        </View>
      </View>
    </View>
  );

  return (
    <ClinicalCanvas style={styles.container}>
      <StatusBar barStyle="dark-content" />
      
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <ChevronLeft size={24} color={theme.colors.primary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Discharge Summary</Text>
        <View style={{ width: 32 }} />
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Patient Banner */}
        <View style={styles.patientBanner}>
          <View style={styles.patientAvatar}>
            <Text style={styles.avatarText}>{patient?.fullName?.charAt(0) || '?'}</Text>
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.patientName}>{patient?.fullName || 'Unknown'}</Text>
            <Text style={styles.patientDiag}>{patient?.diagnosis || 'No diagnosis'}</Text>
          </View>
          <View style={[styles.statusBadge, { backgroundColor: patient?.status === 'Discharged' ? '#D1FAE5' : '#EFF6FF' }]}>
            <Text style={[styles.statusText, { color: patient?.status === 'Discharged' ? '#047857' : '#3B82F6' }]}>
              {patient?.status || 'Admitted'}
            </Text>
          </View>
        </View>

        {/* Generate New Summary Section */}
        <View style={styles.generateSection}>
          <Text style={styles.sectionTitle}>Generate New Summary</Text>
          <Text style={styles.inputLabel}>Follow-up Instructions</Text>
          <TextInput
            style={styles.followUpInput}
            placeholder="Enter follow-up instructions..."
            placeholderTextColor={theme.colors.textSecondary}
            value={followUp}
            onChangeText={setFollowUp}
            multiline
            numberOfLines={3}
          />
          <TouchableOpacity 
            style={styles.generateBtn}
            onPress={handleGenerate}
            disabled={generating}
            activeOpacity={0.8}
          >
            {generating ? (
              <ActivityIndicator size="small" color="#FFF" />
            ) : (
              <>
                <FileCheck size={18} color="#FFF" />
                <Text style={styles.generateBtnText}>Generate & Save Summary</Text>
              </>
            )}
          </TouchableOpacity>
        </View>

        {/* Existing Summaries */}
        <Text style={styles.sectionTitle}>Previous Summaries</Text>
        
        {loading ? (
          <View style={styles.loaderBox}>
            <ActivityIndicator size="small" color={theme.colors.primary} />
            <Text style={styles.loaderText}>Loading summaries...</Text>
          </View>
        ) : summaries.length === 0 ? (
          <View style={styles.emptyBox}>
            <FileCheck size={32} color="#D1D5DB" />
            <Text style={styles.emptyText}>No discharge summaries generated yet.</Text>
          </View>
        ) : (
          summaries.map((s, idx) => renderSummaryCard(s, idx))
        )}
      </ScrollView>
    </ClinicalCanvas>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.sm,
    backgroundColor: theme.colors.surface, borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  backBtn: { padding: theme.spacing.xs },
  headerTitle: { ...theme.typography.h2, color: theme.colors.primary, fontWeight: '800' },
  scrollContent: { padding: theme.spacing.lg, paddingBottom: 80 },

  patientBanner: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.xl, padding: theme.spacing.lg, marginBottom: theme.spacing.lg,
  },
  patientAvatar: {
    width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center', justifyContent: 'center', marginRight: theme.spacing.md,
  },
  avatarText: { fontSize: 18, fontWeight: '800', color: '#FFF' },
  patientName: { fontSize: 16, fontWeight: '800', color: '#FFF' },
  patientDiag: { fontSize: 12, color: '#93C5FD', fontWeight: '500' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 11, fontWeight: '700' },

  generateSection: {
    backgroundColor: '#FFF', borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.xl, marginBottom: theme.spacing.xl,
    borderWidth: 1, borderColor: '#E2E8F0',
  },
  sectionTitle: { ...theme.typography.h3, marginBottom: theme.spacing.md },
  inputLabel: { ...theme.typography.label, marginBottom: theme.spacing.xs, color: theme.colors.textSecondary },
  followUpInput: {
    backgroundColor: '#F8FAFC', borderRadius: theme.borderRadius.md, borderWidth: 1,
    borderColor: '#E2E8F0', padding: theme.spacing.md, ...theme.typography.body,
    minHeight: 80, textAlignVertical: 'top', marginBottom: theme.spacing.md,
  },
  generateBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#047857', borderRadius: theme.borderRadius.lg,
    paddingVertical: 14, gap: 8,
  },
  generateBtnText: { color: '#FFF', fontSize: 14, fontWeight: '700' },

  summaryCard: {
    backgroundColor: '#FFF', borderRadius: theme.borderRadius.xl,
    borderWidth: 1, borderColor: '#E2E8F0', marginBottom: theme.spacing.lg, overflow: 'hidden',
  },
  summaryHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: '#F0FDF4', paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.md,
    borderBottomWidth: 1, borderBottomColor: '#E2E8F0',
  },
  summaryBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  summaryBadgeText: { fontSize: 13, fontWeight: '700', color: '#047857' },
  shareBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: '#EFF6FF' },
  shareBtnText: { fontSize: 12, fontWeight: '700', color: theme.colors.primary },

  summarySection: { padding: theme.spacing.lg },
  summaryRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  summaryLabel: { fontSize: 12, color: '#6B7280', fontWeight: '600', flex: 1 },
  summaryValue: { fontSize: 13, fontWeight: '700', color: '#1F2937' },
  summaryDivider: { height: 1, backgroundColor: '#F1F5F9', marginHorizontal: theme.spacing.lg },

  fieldBlock: { marginBottom: theme.spacing.md },
  fieldHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  fieldTitle: { fontSize: 12, fontWeight: '700', color: '#374151' },
  fieldContent: { fontSize: 13, color: '#4B5563', lineHeight: 20, paddingLeft: 20 },

  summaryFooter: {
    backgroundColor: '#F8FAFC', paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.sm,
    borderTopWidth: 1, borderTopColor: '#F1F5F9', flexDirection: 'row', justifyContent: 'space-between',
  },
  footerRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  footerText: { fontSize: 10, color: '#9CA3AF', fontWeight: '500' },

  loaderBox: { alignItems: 'center', paddingVertical: 40 },
  loaderText: { marginTop: 8, color: theme.colors.textSecondary, fontSize: 12 },
  emptyBox: { alignItems: 'center', paddingVertical: 40, gap: 8 },
  emptyText: { color: '#9CA3AF', fontSize: 13 },
});

export default DischargeSummaryScreen;
